# -*- coding: utf-8 -*-
"""Assignment 3 Q2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xavCETp1chS6PFEdf1uVFXNPSJDw_Scs
"""

Write a Python program to reverse a string.

def reverse(string):
    string = list(string)
    string.reverse()
    return "".join(string)
 
j = '"abcd1234"'
 
print("The reversed string is : ", reverse(j))